"""empty message

Revision ID: 67328edd3eb1
Revises: 133a89f2c1ed
Create Date: 2024-04-03 14:45:24.907470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67328edd3eb1'
down_revision: Union[str, None] = '133a89f2c1ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Doctor_full_name_key', 'Doctor', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Doctor_full_name_key', 'Doctor', ['full_name'])
    # ### end Alembic commands ###
