"""empty message

Revision ID: 7dfe4c4fcf20
Revises: ac4f9f63ea76
Create Date: 2024-04-03 21:32:02.698923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dfe4c4fcf20'
down_revision: Union[str, None] = 'ac4f9f63ea76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Patient', 'bdate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Patient', sa.Column('bdate', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
