"""empty message

Revision ID: 92bff0f4d5e7
Revises: 7dfe4c4fcf20
Create Date: 2024-04-03 21:36:09.836673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92bff0f4d5e7'
down_revision: Union[str, None] = '7dfe4c4fcf20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Patient', sa.Column('bdate', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Patient', 'bdate')
    # ### end Alembic commands ###
