# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chek_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_chek_admin(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(718, 262)
        Form.setStyleSheet("")
        self.push_button_yes = QtWidgets.QPushButton(Form)
        self.push_button_yes.setGeometry(QtCore.QRect(130, 150, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.push_button_yes.setFont(font)
        self.push_button_yes.setStyleSheet("")
        self.push_button_yes.setObjectName("push_button_yes")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(60, 50, 591, 61))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textBrowser.setObjectName("textBrowser")
        self.push_button_no = QtWidgets.QPushButton(Form)
        self.push_button_no.setGeometry(QtCore.QRect(400, 150, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.push_button_no.setFont(font)
        self.push_button_no.setStyleSheet("")
        self.push_button_no.setObjectName("push_button_no")
        self.push_button_right = QtWidgets.QPushButton(Form)
        self.push_button_right.setGeometry(QtCore.QRect(100, 60, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.push_button_right.setFont(font)
        self.push_button_right.setStyleSheet("")
        self.push_button_right.setObjectName("push_button_right")
        self.push_button_vran = QtWidgets.QPushButton(Form)
        self.push_button_vran.setGeometry(QtCore.QRect(520, 60, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.push_button_vran.setFont(font)
        self.push_button_vran.setStyleSheet("")
        self.push_button_vran.setObjectName("push_button_vran")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, -220, 751, 511))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(
            "../../OneDrive/Изображения/Снимки экрана/Снимок экрана 2024-03-31 113316.png"))
        self.label.setObjectName("label")
        self.label.raise_()
        self.push_button_yes.raise_()
        self.textBrowser.raise_()
        self.push_button_no.raise_()
        self.push_button_right.raise_()
        self.push_button_vran.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.push_button_yes.setText(_translate("Form", "Да-да"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Вы точно администратор???</span></p></body></html>"))
        self.push_button_no.setText(_translate("Form", "Нет)"))
        self.push_button_right.setText(_translate("Form", "???"))
        self.push_button_vran.setText(_translate("Form", "???"))
