# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'glav_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_main_menu(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(508, 724)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, -10, 511, 741))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(
            "../../OneDrive/Изображения/Снимки экрана/Снимок экрана 2024-03-31 112922.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.push_button_like_admin = QtWidgets.QPushButton(Form)
        self.push_button_like_admin.setGeometry(QtCore.QRect(0, 450, 511, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.push_button_like_admin.setFont(font)
        self.push_button_like_admin.setAutoFillBackground(False)
        self.push_button_like_admin.setStyleSheet("")
        self.push_button_like_admin.setAutoRepeatDelay(300)
        self.push_button_like_admin.setObjectName("push_button_like_admin")
        self.push_button_like_patient = QtWidgets.QPushButton(Form)
        self.push_button_like_patient.setGeometry(QtCore.QRect(0, 360, 511, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.push_button_like_patient.setFont(font)
        self.push_button_like_patient.setAutoFillBackground(False)
        self.push_button_like_patient.setStyleSheet("")
        self.push_button_like_patient.setAutoRepeatDelay(300)
        self.push_button_like_patient.setObjectName("push_button_like_patient")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        Form.setToolTip(_translate("Form", "<html><head/><body><p>file:///C:/Users/HP/OneDrive/Изображения/Снимки экрана/Снимок экрана 2024-03-30 212547.png</p></body></html>"))
        self.push_button_like_admin.setText(_translate("Form", "Войти от имени администратора"))
        self.push_button_like_patient.setText(_translate("Form", "Войти как пациент"))
