# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'service_update.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_update(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(421, 344)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 170, 130, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line_edit_price1 = QtWidgets.QLineEdit(self.groupBox)
        self.line_edit_price1.setGeometry(QtCore.QRect(150, 230, 251, 28))
        self.line_edit_price1.setObjectName("line_edit_price1")
        self.line_edit_doctor_id1 = QtWidgets.QLineEdit(self.groupBox)
        self.line_edit_doctor_id1.setGeometry(QtCore.QRect(150, 100, 251, 28))
        self.line_edit_doctor_id1.setObjectName("line_edit_doctor_id1")
        self.line_edit_title1 = QtWidgets.QLineEdit(self.groupBox)
        self.line_edit_title1.setGeometry(QtCore.QRect(150, 160, 251, 28))
        self.line_edit_title1.setObjectName("line_edit_title1")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 110, 113, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 230, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.push_button_save1 = QtWidgets.QPushButton(self.groupBox)
        self.push_button_save1.setGeometry(QtCore.QRect(150, 280, 241, 31))
        self.push_button_save1.setObjectName("push_button_save1")
        self.push_button_undo1 = QtWidgets.QPushButton(self.groupBox)
        self.push_button_undo1.setGeometry(QtCore.QRect(20, 280, 121, 31))
        self.push_button_undo1.setObjectName("push_button_undo1")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(60, 60, 41, 20))
        self.label_4.setObjectName("label_4")
        self.label_id = QtWidgets.QLabel(self.groupBox)
        self.label_id.setGeometry(QtCore.QRect(150, 50, 181, 31))
        self.label_id.setText("")
        self.label_id.setObjectName("label_id")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Обновить услугу"))
        self.label_2.setText(_translate("Form", "Название услуги"))
        self.label.setText(_translate("Form", "     id врача     "))
        self.label_3.setText(_translate("Form", "        Цена"))
        self.push_button_save1.setText(_translate("Form", "Сохранить"))
        self.push_button_undo1.setText(_translate("Form", "Отмена"))
        self.label_4.setText(_translate("Form", "id"))
